### ISSUE TITLE
大佬，求sql学习一下

### ISSUE THREAD

**Issue by arraycto** [Huangjie-Github/hotel#1]
大佬您好，求项目的sql文件和测试数据学习一下，谢谢，目前无sql，项目无法运行，感谢

**Comment by Huangjie-Github** [comment]
晚点上传

**Comment by Huangjie-Github** [comment]
> 大佬您好，求项目的sql文件和测试数据学习一下，谢谢，目前无sql，项目无法运行，感谢

晚点上传

**Comment by arraycto** [comment]
期待期待

**Comment by Huangjie-Github** [comment]
好的  待会儿发你  现在在吃饭------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;ali_zhang&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月17日(星期天) 中午1:37
收件人:&nbsp;&quot;Huangjie-Github/hotel&quot;<hotel@noreply.github.com&gt;;
抄送:&nbsp;&quot;Huangjie-Github&quot;<1728537059@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Huangjie-Github/hotel] 大佬，求sql学习一下 (#1)

**Comment by Huangjie-Github** [comment]
已经上传完毕  在源代码目录  hotel.sql ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;ali_zhang&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月17日(星期天) 下午2:45
收件人:&nbsp;&quot;Huangjie-Github/hotel&quot;<hotel@noreply.github.com&gt;;
抄送:&nbsp;&quot;Huangjie-Github&quot;<1728537059@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Huangjie-Github/hotel] 大佬，求sql学习一下 (#1)

**Comment by kaiwenli** [comment]
麻烦您尽快删除一下https://github.com/arraycto/kwc_wpm  这个版本库吧。着急！ 谢谢！

我的电话是：189 1130 0582

**Comment by Huangjie-Github** [comment]
我没有引用这个版本库吧https://github.com/arraycto/kwc_wpm------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年3月24日(星期三) 上午9:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Huangjie-Github/hotel] 大佬，求sql学习一下 (#1)

**Comment by kaiwenli** [comment]
@arraycto  他的版本库里面放了这个版本库。这个版本库出问题了，必须要及时下架。联系不到所有人了。请了解。

**Comment by Huangjie-Github** [comment]
他用这个版本库涉及到啥问题了吗------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年3月24日(星期三) 下午3:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Huangjie-Github/hotel] 大佬，求sql学习一下 (#1)
